name: concat

on: [push, workflow_dispatch]

jobs: 
  concat:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup datetuil
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - name: concat
      run:  python3 lecture.py
    - name: Pushback
      run: bash ./pushback.sh